### ISSUE TITLE
Tests are failing when cloning repo and running tests

### ISSUE THREAD

**Issue by macklinu** [probot/unfurl#31]
Steps to reproduce:

* clone the repo
* run `npm install`
* run `npm test`

Expected: All tests pass

Actual: Tests are failing
```
❯ npm test

> unfurl@1.0.0 test /Users/macklinu/dev/probot/unfurl
> jest && standard

 FAIL  test/index.test.js
  ● Test suite failed to run

    SecurityError: localStorage is not available for opaque origins

      at Window.get localStorage [as localStorage] (node_modules/jsdom/lib/jsdom/browser/Window.js:257:15)
          at Array.forEach (<anonymous>)

 FAIL  test/get-links.test.js
  ● Test suite failed to run

    SecurityError: localStorage is not available for opaque origins

      at Window.get localStorage [as localStorage] (node_modules/jsdom/lib/jsdom/browser/Window.js:257:15)
          at Array.forEach (<anonymous>)

 FAIL  test/unfurl-to-attachment.test.js
  ● Test suite failed to run

    SecurityError: localStorage is not available for opaque origins

      at Window.get localStorage [as localStorage] (node_modules/jsdom/lib/jsdom/browser/Window.js:257:15)
          at Array.forEach (<anonymous>)

Test Suites: 3 failed, 3 total
Tests:       0 total
Snapshots:   0 total
Time:        0.868s, estimated 2s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
```

Versions:

* npm: 6.4.1
* node: 8.11.3

**Comment by macklinu** [comment]
The above failure seems related to https://github.com/facebook/jest/issues/6766. When I update to the latest version of Jest locally (23.6.0) and run `npm test`, I see a different issue:

```
❯ npm test

> unfurl@1.0.0 test /Users/macklinu/dev/probot/unfurl
> jest && standard

 PASS  test/unfurl-to-attachment.test.js
 PASS  test/get-links.test.js

 RUNS  test/index.test.js

Test Suites: 2 passed, 2 of 3 total
Tests:       10 passed, 10 total
Snapshots:   0 total
Time:        3s00:03:39.678Z ERROR event:
  request to https://api.github.com/app/installations/13055/access_tokens failed, reason: Nock: No match for request {
    "method": "POST",
    "url": "https://api.github.com/app/installations/13055/access_tokens",
    "headers": {
      "accept": [
        "application/vnd.github.machine-man-preview+json"
      ],
      "user-agent": [
        "octokit/rest.js v15.11.2"
      ],
      "authorization": [
        "Bearer jwt"
      ],
      "content-length": [
        "0"
      ],
      "accept-encoding": [
        "gzip,deflate"
      ],
      "connection": [
        "close"
      ]
    }
  }
  --
  request to https://api.github.com/app/installations/13055/access_tokens failed, reason: Nock: No match for request {
    "method": "POST",
    "url": "https://api.github.com/app/installations/13055/access_tokens",
    "headers": {
      "accept": [
        "application/vnd.github.machine-man-preview+json"
      ],
      "user-agent": [
        "octokit/rest.js v15.11.2"
      ],
      "authorization": [
        "Bearer jwt"
      ],
      "content-length": [
        "0"
      ],
      "accept-encoding": [
        "gzip,deflate"
      ],
      "connection": [
        "close"
      ]
    }
  }
      at fetch.then.then.catch.error (/Users/macklinu/dev/probot/unfurl/node_modules/@octokit/rest/lib/request/request.js:105:13)
      at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:228:7)
 FAIL  test/index.test.js
  ● unfurls comments

    request to https://api.github.com/app/installations/13055/access_tokens failed, reason: Nock: No match for request {
      "method": "POST",
      "url": "https://api.github.com/app/installations/13055/access_tokens",
      "headers": {
        "accept": [
          "application/vnd.github.machine-man-preview+json"
        ],
        "user-agent": [
          "octokit/rest.js v15.11.2"
        ],
        "authorization": [
          "Bearer jwt"
        ],
        "content-length": [
          "0"
        ],
        "accept-encoding": [
          "gzip,deflate"
        ],
        "connection": [
          "close"
        ]
      }
    }

      at fetch.then.then.catch.error (node_modules/@octokit/rest/lib/request/request.js:105:13)

Test Suites: 1 failed, 2 passed, 3 total
Tests:       1 failed, 10 passed, 11 total
Snapshots:   0 total
Time:        3.148s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
```

Perhaps this is related in some way to #26 or #28 (a network request is being mocked properly)?

**Comment by macklinu** [comment]
still relevant

**Comment by macklinu** [comment]
still relevant

**Comment by Atinux** [comment]
😂
